# Managed by Puppet!

############################################################
# Common Bash Settings
############################################################


# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# History control
HISTCONTROL=ignoredups:ignorespace
HISTSIZE=100000
HISTFILESIZE=2000000
shopt -s histappend
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a;"