# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/reduxjs/redux/blob/master/CONTRIBUTING.md#building-redux
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: npm
      directives:
        description: Install JetBrains.Toolbox
        allowPrerelease: true
      settings:
        id: JetBrains.Toolbox
        source: winget